/*

Orders

*/




INSERT INTO `Order` (`id`, `created_date`, `name`, `runtype`, `description`, `finished_date`, `workgroup`) VALUES

('1485263', '2024-01-12', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1485457', '2024-01-15', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1485458', '2024-01-15', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1485460', '2024-01-15', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1485461', '2024-01-15', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1486064', '2024-01-16', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1486066', '2024-01-16', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1486673', '2024-01-18', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1490228', '2024-02-01', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1'),
('1490402', '2024-02-02', 'Automatic allocation', 'NPKA1', '', '2024-01-01', 'NKA1');





/*

Supplier

*/



INSERT INTO `Customer` (`code`, `name`, `address1`, `address2`, `address3`, `address4`, `address5`, `address6`, `postcode`, `countrycode`, `contact`, `telephone`, `email`, `best_name`, `country`, `despatch_method`, `despatch_method_name`, `despatch_customer_code`, `despatch_customer_address_id`, `line`, `main_contact_firstname`, `main_contact_surname`, `main_contact_title`, `main_contact_email`, `main_contact_telephone`, `invoice_contact_firstname`, `invoice_contact_surname`, `invoice_contact_title`, `invoice_contact_email`, `invoice_contact_telephone`, `vat_number`) VALUES
('BOTRAN22', 'Tim Marner Ltd', '', '22 Chorley New Road', '', 'Bolton', 'Lancashire', 'United Kingdom', 'BL1 4AP', 'GB', 'Betty Court', '01204393048', 'betty@timmarner.co.uk', 'Tim Marner Ltd', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'BOTRAN22', '000002', '7012555', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('CKGUARD', 'Guardian', 'Guardian Automotive Ltd', 'Unit 3a, Collingwood Road', 'West Moors', 'Wimborne', 'Dorset', 'United Kingdom', 'BH21 6QF', 'GB', 'Laura Wright', '', 'daniel@guardianauto.co.uk', 'Guardian', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'CKGUARD', '', '7060066', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('DPABEL23', 'Abel & Imray', 'Abel & Imray', 'james street west', '', 'bath', '', 'United Kingdom', 'BA1 2DA', 'GB', 'John Austin-Brooks', '', 'John.Austin-Brooks@abelimray.com', 'Abel & Imray', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'DPABEL23', '', '7105412', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('EDKIDS24', 'Kids Operating Room', '', '107/3 George Street', '', 'Edinburgh', '', 'United Kingdom', 'EH2 3ES', 'GB', 'Jessica Lechmere', '', 'rosa@kidsor.org', 'Kids Operating Room', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'EDKIDS24', '', '6968097', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('EXEXCI', 'Exeter City Community Trust', '', 'St. James Park', 'Stadium Way', 'Exeter', 'Devon', 'United Kingdom', 'EX4 6PX', 'GB', 'Adam Williams', '07827 871721', 'danny.harris@ecfc.co.uk', 'Exeter City Community Trust', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'EXEXCI', '', '7045641', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('EXUEDPS', 'Thea Collins - University of Exeter', 'University of Exeter', 'Streatham Campus, Mail Room', '', 'Exeter', 'Devon', 'United Kingdom', 'EX4 4QJ', 'GB', 'Thea Collins', '01392 723498', 'J.Spruit@exeter.ac.uk', 'Thea Collins - University of Exeter', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'EXUEDPS', '000037', '6946703', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('FRDAVD', 'Nettl.com (Stockport)', 'Davora Limited', '135 Heaton Moor Road', '', 'Stockport', '', 'United Kingdom', 'SK4 4HY', 'GB', 'Rajeev Arora', '0161 975 5203', 'rajeev@davora.co.uk', 'Nettl.com (Stockport)', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'FRDAVD', '', '7027518', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('FRF442', 'Chippenham', 'Digiprint Chippenham Ltd', '5 New Road', '', 'Chippenham', '', 'United Kingdom', 'SN15 1EJ', 'GB', 'Ben Gregory', '', 'Info@digiprintgroup.com', 'Chippenham', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'FRF442', '', '6916096', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('FRGLSO', 'printing.com Glasgow South', 'Creative Concept UK Limited', '614 Eglinton Street', '', 'Glasgow', '', 'United Kingdom', 'G5 9RR', 'GB', 'Andy Hart', '07968 417 357', 'andy@soapboxdigital.co.uk', 'printing.com Glasgow South', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'FRGLSO', '', '6987172', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('FRIDIC', 'printing.com Doncaster', 'Idea Icon Limited', '4 Milethorn Lane', '', 'Doncaster', 'South Yorkshire', 'United Kingdom', 'DN1 2SU', 'GB', 'Ian Kendall', '01984 935831', 'accounts@heatherbankprint.com', 'printing.com Doncaster', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'FRIDIC', '', '6868972', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('FRKKPR', 'Athlone Printing', 'Keith Nolan', 'St Marys Square', 'Athlone', 'Athlone', ' Westmeath', 'Republic of Ireland', 'N37TH58', 'IE', 'Printing.com Athlone', '00353 87 289 2537', 'athlone@printing.com', 'Athlone Printing', 'Republic of Ireland', '18', 'UPS Standard - IE', 'FRKKPR', '', '6952380', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('FRN054', 'ECG Facility Services', 'E C G Building Maintenance', 'Unit 11, Block 2, First Road', 'Blantyre Industrial Estate, Blantyre', 'Glasgow', '', 'United Kingdom', 'G72 0ND', 'GB', 'Angela Miller', '', '', 'ECG Facility Services', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'FRN054', '000192', '6976357', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('FRN086', 'Nettl of Talbot Green', 'Trustmark Design & Print Limited', '30 Talbot Road, Talbot Green', '', 'Pontyclun', 'Mid Glamorgan', 'United Kingdom', 'CF72 8AF', 'GB', 'Haydn Pryor', '', 'accounts@trustmark.uk.com', 'Nettl of Talbot Green', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'FRN086', '', '6968817', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('GLOSMONT', 'Montpellier Legal', '', 'Festival House', 'Jessop Avenue', 'Cheltenham', 'Gloucestershire', 'United Kingdom', 'GL50 3SH', 'GB', 'Nick Ponting', '', 'simon@montpellier.legal', 'Montpellier Legal', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'GLOSMONT', '', '6910932', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('GNCARR22', 'Carroll Group Ltd', '', 'Unit 9 Maritime Trade Park', 'Atlas Road', 'Bootle', 'Merseyside', 'United Kingdom', 'L20 4DY', 'GB', 'Steph Bagot', '', '', 'Carroll Group Ltd', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'GNCARR22', '', '6909183', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('IGORDERS', 'Image Group', 'Works Mcr', 'Eighth Street, Second Avenue', 'Trafford Park', 'Manchester', '', 'United Kingdom', 'M17 1FG', 'GB', 'Pati Correro', '0161 707 8886', 'patricia.correro@worksmcr.com', 'Image Group', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'IGORDERS', '', '6913202', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('JLMOORSI', 'Moorside High School', 'Moorside High School', '57 Deans Road', 'Swinton', 'Manchester', '', 'United Kingdom', 'M27 0AP', 'GB', 'Helen  Ryles-Dean', '0781 809 5239', 'Helen.Ryles-Dean@consilium-at.com', 'Moorside High School', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'JLMOORSI', '', '7044284', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('JLSCAL22', 'Ready Steady Store', '', '30 Shield Drive', 'Wardley Industrial Estate, Worsley', 'Manchester', '', 'United Kingdom', 'M28 2QB', 'GB', 'Peter tobolski', '07973 197155', 'info@scalpsolutions.uk.com', 'Ready Steady Store', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'JLSCAL22', '000003', '6964672', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('LBKKAN', '.', '', '1 Hackett Street', 'Cofton Hackett', 'Birmingham', '', 'United Kingdom', 'B45 8FT', 'GB', 'Ashlea Smith', '', '', '.', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'LBKKAN', '000005', '6917379', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('N0NISC22', 'NI Science Festival', '', '3rd floor, Botanic House', '1-5 Botanic Avenue', 'Belfast', 'Antrim', 'United Kingdom', 'BT7 1JG', 'GB', 'Aoife Earley', '07706833508', 'aoife@nisciencefestival.com', 'NI Science Festival', 'United Kingdom', 'NQ', 'Works maker : Northern Ireland', 'N0NISC22', '', '7076864', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('N1WEST43', 'Westcotec', 'Westcotec Ltd', '34 Bertie Ward Way', '', 'Dereham', 'Norfolk', 'United Kingdom', 'NR19 1TE', 'GB', 'Will Spinks', '+44 1362 853124', 'will.spinks@westcotec.co.uk', 'Westcotec', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'N1WEST43', '', '6931264', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('NTALIS2M', 'Alison Stewart', '', '6 Townsend Walk', 'Kempston', 'Bedford', 'Bedfordshire', 'United Kingdom', 'MK42 7GX', 'GB', 'Alison Stewart', '07966462582', 'alstew21_4@hotmail.com', 'Alison Stewart', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'NTALIS2M', '', '6957252', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('OGKELLYL', 'Kelly Louise Fitness', '', '24 Expectations Drive', '', 'Rugby', 'Warwickshire', 'United Kingdom', 'CV21 1FW', 'GB', 'Kelly Louise', '07733 428428', 'kellylouisefitness2021@gmail.com', 'Kelly Louise Fitness', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'OGKELLYL', '', '7073944', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('ORDISHOM', 'Permit Room - PR1', '', '31a-32, East Street', '', 'Brighton', 'East Sussex', 'United Kingdom', 'BN1 1HL', 'GB', '', '07482 620127', '', 'Permit Room - PR1', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'ORDISHOM', '000001', '6967557', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('PVSERV22', 'ServiceMax Europe Ltd', '', '6 Oaktree Walk', '', 'Caterham', 'Surrey', 'United Kingdom', 'CR3 5JZ', 'GB', 'Anthony Harris', '', '', 'ServiceMax Europe Ltd', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'PVSERV22', '000009', '6933267', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WM100A22', 'UKSI', '', 'Lilleshall National Sports Centre,, Lilleshall', '', 'Newport', 'Shropshire', 'United Kingdom', 'TF10 9AT', 'GB', 'Faye Hodson', '07754 391829', '', 'UKSI', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'WM100A22', '000285', '7051848', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WMCOLO26', 'Horticap', '', 'Bluecoat Wood Nurseries, Otley Road, Beckwithshaw', '', 'Harrogate', 'North Yorkshire', 'United Kingdom', 'HG3 1QL', 'GB', 'Gilvray Croudson', '01423 522876', '', 'Horticap', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'WMCOLO26', '000048', '7090306', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WMDEFI24', 'Definition Print Management Ltd', '', 'UNIT E6, Block E ', 'South City Business Park, Tallaght', 'Dublin', 'Dublin 24', 'Republic of Ireland', 'D24CH56', 'IE', 'John Kelly', '00 353 86 8321821', 'john@definitionprint.ie', 'Definition Print Management Ltd', 'Republic of Ireland', '18', 'UPS Standard - IE', 'WMDEFI24', '', '6917230', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WMFOOT22', 'Fever & Boutique ', '', 'Formally Rococo', 'Mary Arches Street', 'EXETER', '', 'United Kingdom', 'EX4 3BA', 'GB', 'Dominic Borg', '01225 706058', '', 'Fever & Boutique ', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'WMFOOT22', '000079', '6925339', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WMFORT23', 'Fortyfour Creative ', '', '44 Diana Gardens, Bradley Stoke', 'Bristol', 'BS32 8DD', 'South Glos', 'United Kingdom', 'BS32 8DD', 'GB', 'Robert Wilson', '01173254455', 'info@44creative.co.uk', 'Fortyfour Creative ', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'WMFORT23', '', '6924786', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WMFUSI24', 'Shawmind', '', '153 Psalter Lane', '', 'Sheffield', 'South Yorkshire', 'United Kingdom', 'S11 8UY', 'GB', 'Peter Wingrove', '07840362377', '', 'Shawmind', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'WMFUSI24', '000093', '6926275', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WMKARO22', 'Green Willow Funerals', '', 'Eclipse House, Coronation Road', '', 'Cardiff', 'South Glamorgan', 'United Kingdom', 'CF14 4QY', 'GB', 'Tracey Smith-Atkins', '02920 524 200', '', 'Green Willow Funerals', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'WMKARO22', '000053', '6953088', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WMOUTH22', 'Wright Renewable Heating', 'Wright Renewable Heating Limited', 'Unit 5, Claylands Avenue', 'Dukeries Industrial Estate', 'Worksop', 'Nottinghamshire', 'United Kingdom', 'S81 7DJ', 'GB', 'Adam Roberts', '01909 813456', '', 'Wright Renewable Heating', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'WMOUTH22', '000041', '7030779', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('WMTHEE22', 'Warwickshire Police Force Headquarters', '', 'Woodcote Drive', 'Leek Wootton', 'Warwick', '', 'United Kingdom', 'CV35 7QA', 'GB', 'FOA: Kate Quilley', '01522 518 100', '', 'Warwickshire Police Force Headquarters', 'United Kingdom', 'NP', 'Works maker : UK Mainland', 'WMTHEE22', '000123', '7086978', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
